// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD69DRZ02ysW0JekhsuZo4KHQYGQaXq7hQ',
    appId: '1:639130500903:web:e99cbc2e8783d7f18e3302',
    messagingSenderId: '639130500903',
    projectId: 'card-ai-app',
    authDomain: 'card-ai-app.firebaseapp.com',
    storageBucket: 'card-ai-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl962wH4xc1RyJWz5Vnu4Qb_6aY4U-Vks',
    appId: '1:639130500903:android:ac2235a3249af5658e3302',
    messagingSenderId: '639130500903',
    projectId: 'card-ai-app',
    storageBucket: 'card-ai-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKVb047INjDjZ_gjy_z8o19S1EIyTx1es',
    appId: '1:639130500903:ios:b25c96d98a90fc548e3302',
    messagingSenderId: '639130500903',
    projectId: 'card-ai-app',
    storageBucket: 'card-ai-app.firebasestorage.app',
    iosBundleId: 'com.example.cardAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKVb047INjDjZ_gjy_z8o19S1EIyTx1es',
    appId: '1:639130500903:ios:b25c96d98a90fc548e3302',
    messagingSenderId: '639130500903',
    projectId: 'card-ai-app',
    storageBucket: 'card-ai-app.firebasestorage.app',
    iosBundleId: 'com.example.cardAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD69DRZ02ysW0JekhsuZo4KHQYGQaXq7hQ',
    appId: '1:639130500903:web:1b007ebb3cc69d9c8e3302',
    messagingSenderId: '639130500903',
    projectId: 'card-ai-app',
    authDomain: 'card-ai-app.firebaseapp.com',
    storageBucket: 'card-ai-app.firebasestorage.app',
  );
}
